# Generated by Django 3.1.4 on 2021-08-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210826_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer'),
        ),
    ]
