# Generated by Django 3.1.4 on 2021-08-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stock', 'Stockable Product'), ('consu', 'Consumable'), ('service', 'Service')], default='stock', max_length=10),
        ),
    ]
