# Generated by Django 3.1.4 on 2021-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210804_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, default=2, upload_to='barcodes/'),
            preserve_default=False,
        ),
    ]
