# Generated by Django 3.1.4 on 2022-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ratings',
            field=models.CharField(blank=True, choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default='one', max_length=10, null=True),
        ),
    ]
