# Generated by Django 3.1.4 on 2021-08-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20210804_1240'),
        ('customer', '0002_customer_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=25, null=True)),
                ('purchase_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('q', 'Quotation'), ('d', 'Draft'), ('c', 'Confirmed'), ('so', 'Purchase Order')], default='q', max_length=2)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='customer.customer')),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'PurchaseOrders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lines', to='product.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lines', to='purchase.purchaseorder')),
            ],
            options={
                'verbose_name': 'PurchaseOrderLine',
                'verbose_name_plural': 'PurchaseOrderLines',
                'unique_together': {('purchase_order', 'product')},
            },
        ),
    ]
