# Generated by Django 3.1.4 on 2021-08-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210809_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='price',
        ),
    ]
