# Generated by Django 3.1.4 on 2021-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
