# Generated by Django 3.1.4 on 2021-08-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_is_vendor'),
        ('inventory', '0003_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='customer.customer'),
        ),
    ]
