# Generated by Django 3.1.4 on 2021-08-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210804_1240'),
        ('inventory', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product'),
            preserve_default=False,
        ),
    ]
