# Generated by Django 3.1.4 on 2021-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210811_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='product_name_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='product-name-lists'),
        ),
    ]
