# Generated by Django 3.1.4 on 2021-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_location_product_name_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='stock_upload')),
            ],
        ),
    ]
