# Generated by Django 3.1.4 on 2021-08-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210804_1240'),
        ('inventory', '0009_stockupload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('location_id', 'product_id')},
        ),
    ]
