# Generated by Django 3.1.4 on 2021-08-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20210804_1240'),
        ('customer', '0002_customer_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=25, null=True)),
                ('order_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('q', 'Quotation'), ('d', 'Draft'), ('c', 'Confirmed'), ('so', 'Sale Order')], default='q', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='product.product')),
            ],
            options={
                'verbose_name': 'SaleOrder',
                'verbose_name_plural': 'SaleOrders',
            },
        ),
    ]
