# Generated by Django 3.1.4 on 2021-08-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210804_1240'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_lines', to='product.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_lines', to='sale.saleorder')),
            ],
            options={
                'verbose_name': 'SaleOrderLine',
                'verbose_name_plural': 'SaleOrderLines',
                'unique_together': {('sale_order', 'product')},
            },
        ),
    ]
