# Generated by Django 3.1.4 on 2021-08-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleorderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='qty',
        ),
    ]
