# Generated by Django 3.1.4 on 2021-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20210805_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
