# Generated by Django 3.1.4 on 2021-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_saleorderline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
