# Generated by Django 3.1.4 on 2021-08-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210806_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderline',
            name='price',
        ),
    ]
