# Generated by Django 3.1.4 on 2021-08-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('o', 'Open'), ('p', 'Paid')], default='q', max_length=1)),
                ('invoice_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
