# Generated by Django 3.1.4 on 2021-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
