# Generated by Django 3.1.4 on 2021-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
