# Generated by Django 3.1.4 on 2021-08-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_remove_purchaseorder_invoice_ids'),
        ('invoice', '0006_invoice_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_invoices', to='purchase.purchaseorder'),
        ),
    ]
